version: '3.4'

services:
  forgeapi:
    image: forgeapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - MONGO_URL: ${MONGO_URL}
    command: npm start
    ports:
      - 5000:5000
